# Generated by Django 2.2.3 on 2019-07-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hackernews_url', models.URLField()),
                ('url', models.URLField()),
                ('posted_on', models.TextField(max_length=50)),
                ('here_posted_on', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
    ]
