# Generated by Django 2.2.3 on 2019-07-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190718_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default='what', max_length=200),
            preserve_default=False,
        ),
    ]
