# Generated by Django 2.2.3 on 2019-07-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='here_posted_on',
        ),
    ]
