# Generated by Django 2.2.3 on 2019-07-18 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_article_here_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='here_posted_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 11, 14, 31, 514105)),
            preserve_default=False,
        ),
    ]
