# Generated by Django 2.2.3 on 2019-07-18 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190718_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='here_posted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='delete_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='read_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
